"""create bodytype model

Revision ID: 1f040d89839f
Revises: f38699ad7735
Create Date: 2024-11-25 11:09:48.425653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f040d89839f'
down_revision = 'f38699ad7735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cars_body_type_id_body_types'), 'body_types', ['body_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cars_body_type_id_body_types'), type_='foreignkey')
        batch_op.drop_column('body_type_id')

    op.drop_table('body_types')
    # ### end Alembic commands ###
